CREATE DATABASE bar_db;
USE bar_db;

CREATE TABLE drinks
(
	id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	drink_name varchar(255) NOT NULL,
	pick_up BOOLEAN DEFAULT false,
  	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);